# Generated by Django 6.0.3 on 2026-03-18 02:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Swimmer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('nationality', models.CharField(default='USA', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=50)),
                ('team_type', models.CharField(choices=[('high_school', 'High School'), ('club', 'Club'), ('college', 'College'), ('national', 'National')], max_length=20)),
                ('country', models.CharField(default='USA', max_length=3)),
                ('state', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField()),
                ('stroke', models.CharField(choices=[('freestyle', 'Freestyle'), ('backstroke', 'Backstroke'), ('breaststroke', 'Breaststroke'), ('butterfly', 'Butterfly'), ('individual_medley', 'Individual Medley')], max_length=20)),
                ('relay', models.BooleanField(default=False)),
                ('gender', models.CharField(max_length=10)),
            ],
            options={
                'unique_together': {('distance', 'stroke', 'relay', 'gender')},
            },
        ),
        migrations.CreateModel(
            name='Meet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('course', models.CharField(choices=[('SCY', 'Short Course Yards'), ('SCM', 'Short Course Meters'), ('LCM', 'Long Course Meters')], max_length=3)),
                ('meet_type', models.CharField(choices=[('dual', 'Dual'), ('invitational', 'Invitational'), ('conference', 'Conference'), ('championship', 'Championship'), ('olympic', 'Olympic')], max_length=30)),
                ('location_city', models.CharField(max_length=100)),
                ('location_state', models.CharField(blank=True, max_length=10)),
                ('location_country', models.CharField(default='USA', max_length=3)),
                ('source', models.CharField(max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-start_date'],
                'unique_together': {('source', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='RecruitingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduation_year', models.IntegerField(blank=True, null=True)),
                ('high_school', models.CharField(blank=True, max_length=255)),
                ('home_state', models.CharField(blank=True, max_length=10)),
                ('verbal_commit_date', models.DateField(blank=True, null=True)),
                ('signed_date', models.DateField(blank=True, null=True)),
                ('power_index', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('swimmer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruiting_profile', to='swimmers.swimmer')),
                ('committed_to_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='swimmers.team')),
            ],
        ),
        migrations.CreateModel(
            name='SwimmerSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('swimcloud', 'SwimCloud'), ('swimrankings', 'SwimRankings'), ('usaswimming', 'USA Swimming'), ('fina', 'FINA')], max_length=20)),
                ('external_id', models.CharField(max_length=255)),
                ('profile_url', models.URLField(blank=True, null=True)),
                ('last_scraped_at', models.DateTimeField(blank=True, null=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('swimmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='swimmers.swimmer')),
            ],
            options={
                'unique_together': {('source', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='SwimTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_seconds', models.DecimalField(decimal_places=4, max_digits=10)),
                ('time_display', models.CharField(max_length=20)),
                ('heat', models.IntegerField(blank=True, null=True)),
                ('lane', models.IntegerField(blank=True, null=True)),
                ('place', models.IntegerField(blank=True, null=True)),
                ('dq', models.BooleanField(default=False)),
                ('splits', models.JSONField(blank=True, null=True)),
                ('source', models.CharField(max_length=20)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times', to='swimmers.event')),
                ('meet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times', to='swimmers.meet')),
                ('swimmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times', to='swimmers.swimmer')),
            ],
            options={
                'indexes': [models.Index(fields=['swimmer', 'event', 'time_seconds'], name='swimmers_sw_swimmer_b555b9_idx')],
                'unique_together': {('swimmer', 'meet', 'event', 'time_seconds')},
            },
        ),
        migrations.CreateModel(
            name='SwimmerTeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_year', models.IntegerField()),
                ('is_current', models.BooleanField(default=False)),
                ('swimmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='swimmers.swimmer')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='swimmers.team')),
            ],
            options={
                'unique_together': {('swimmer', 'team', 'season_year')},
            },
        ),
    ]
