# Generated by Django 6.0.3 on 2026-03-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimmers', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meet',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='meet',
            name='source',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddConstraint(
            model_name='meet',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__gt', '')), fields=('source', 'external_id'), name='unique_meet_source_external_id'),
        ),
    ]
