# Generated by Django 6.0.3 on 2026-03-25 05:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('swimmer_times', 'Swimmer Times'), ('team_roster', 'Team Roster'), ('meet_results', 'Meet Results'), ('bulk_import', 'Bulk Import')], max_length=50)),
                ('source', models.CharField(choices=[('swimcloud', 'SwimCloud'), ('swimrankings', 'SwimRankings'), ('usaswimming', 'USA Swimming'), ('fina', 'FINA')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial')], max_length=20)),
                ('parameters', models.JSONField(default=dict)),
                ('result_summary', models.JSONField(blank=True, null=True)),
                ('error_detail', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('triggered_by', models.CharField(choices=[('schedule', 'Schedule'), ('api', 'API'), ('admin', 'Admin')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapeJobLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=10)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='scraping.scrapejob')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
